// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.24.4
// source: indexation/indexation.proto

package indexationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method int32

const (
	Method_NULL            Method = 0
	Method_UPSERT_ARTICLE  Method = 1
	Method_UPSERT_ARTICLES Method = 2
	Method_GET_ARTICLES    Method = 3
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "NULL",
		1: "UPSERT_ARTICLE",
		2: "UPSERT_ARTICLES",
		3: "GET_ARTICLES",
	}
	Method_value = map[string]int32{
		"NULL":            0,
		"UPSERT_ARTICLE":  1,
		"UPSERT_ARTICLES": 2,
		"GET_ARTICLES":    3,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_indexation_indexation_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_indexation_indexation_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_indexation_indexation_proto_rawDescGZIP(), []int{0}
}

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang          int32                  `protobuf:"varint,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_indexation_indexation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_indexation_indexation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_indexation_indexation_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Article) GetLang() int32 {
	if x != nil {
		return x.Lang
	}
	return 0
}

func (x *Article) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UpsertArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertArticleResponse) Reset() {
	*x = UpsertArticleResponse{}
	mi := &file_indexation_indexation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertArticleResponse) ProtoMessage() {}

func (x *UpsertArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexation_indexation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertArticleResponse.ProtoReflect.Descriptor instead.
func (*UpsertArticleResponse) Descriptor() ([]byte, []int) {
	return file_indexation_indexation_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertArticleResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpsertArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        []bool                 `protobuf:"varint,1,rep,packed,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertArticlesResponse) Reset() {
	*x = UpsertArticlesResponse{}
	mi := &file_indexation_indexation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertArticlesResponse) ProtoMessage() {}

func (x *UpsertArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexation_indexation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertArticlesResponse.ProtoReflect.Descriptor instead.
func (*UpsertArticlesResponse) Descriptor() ([]byte, []int) {
	return file_indexation_indexation_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertArticlesResponse) GetStatus() []bool {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpsertArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertArticlesRequest) Reset() {
	*x = UpsertArticlesRequest{}
	mi := &file_indexation_indexation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertArticlesRequest) ProtoMessage() {}

func (x *UpsertArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexation_indexation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertArticlesRequest.ProtoReflect.Descriptor instead.
func (*UpsertArticlesRequest) Descriptor() ([]byte, []int) {
	return file_indexation_indexation_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertArticlesRequest) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type GetArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesRequest) Reset() {
	*x = GetArticlesRequest{}
	mi := &file_indexation_indexation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesRequest) ProtoMessage() {}

func (x *GetArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexation_indexation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesRequest.ProtoReflect.Descriptor instead.
func (*GetArticlesRequest) Descriptor() ([]byte, []int) {
	return file_indexation_indexation_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticlesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetArticlesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           [][]byte               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticlesResponse) Reset() {
	*x = GetArticlesResponse{}
	mi := &file_indexation_indexation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticlesResponse) ProtoMessage() {}

func (x *GetArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexation_indexation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticlesResponse.ProtoReflect.Descriptor instead.
func (*GetArticlesResponse) Descriptor() ([]byte, []int) {
	return file_indexation_indexation_proto_rawDescGZIP(), []int{5}
}

func (x *GetArticlesResponse) GetIds() [][]byte {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_indexation_indexation_proto protoreflect.FileDescriptor

var file_indexation_indexation_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43, 0x0a, 0x07, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f,
	0x0a, 0x15, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x30, 0x0a, 0x16, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x48, 0x0a, 0x15, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x22, 0x42, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22,
	0x27, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x03, 0x69, 0x64, 0x73, 0x2a, 0x4d, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e,
	0x55, 0x50, 0x53, 0x45, 0x52, 0x54, 0x5f, 0x41, 0x52, 0x54, 0x49, 0x43, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x55, 0x50, 0x53, 0x45, 0x52, 0x54, 0x5f, 0x41, 0x52, 0x54, 0x49, 0x43,
	0x4c, 0x45, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x47, 0x45, 0x54, 0x5f, 0x41, 0x52, 0x54,
	0x49, 0x43, 0x4c, 0x45, 0x53, 0x10, 0x03, 0x32, 0xfe, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0d, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x1a, 0x21, 0x2e, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x57, 0x0a, 0x0e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x73, 0x12, 0x21, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x78, 0x33, 0x61, 0x2e,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3b, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_indexation_indexation_proto_rawDescOnce sync.Once
	file_indexation_indexation_proto_rawDescData []byte
)

func file_indexation_indexation_proto_rawDescGZIP() []byte {
	file_indexation_indexation_proto_rawDescOnce.Do(func() {
		file_indexation_indexation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexation_indexation_proto_rawDesc), len(file_indexation_indexation_proto_rawDesc)))
	})
	return file_indexation_indexation_proto_rawDescData
}

var file_indexation_indexation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_indexation_indexation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_indexation_indexation_proto_goTypes = []any{
	(Method)(0),                    // 0: indexation.Method
	(*Article)(nil),                // 1: indexation.Article
	(*UpsertArticleResponse)(nil),  // 2: indexation.UpsertArticleResponse
	(*UpsertArticlesResponse)(nil), // 3: indexation.UpsertArticlesResponse
	(*UpsertArticlesRequest)(nil),  // 4: indexation.UpsertArticlesRequest
	(*GetArticlesRequest)(nil),     // 5: indexation.GetArticlesRequest
	(*GetArticlesResponse)(nil),    // 6: indexation.GetArticlesResponse
}
var file_indexation_indexation_proto_depIdxs = []int32{
	1, // 0: indexation.UpsertArticlesRequest.articles:type_name -> indexation.Article
	1, // 1: indexation.Indexation.UpsertArticle:input_type -> indexation.Article
	4, // 2: indexation.Indexation.UpsertArticles:input_type -> indexation.UpsertArticlesRequest
	5, // 3: indexation.Indexation.GetArticles:input_type -> indexation.GetArticlesRequest
	2, // 4: indexation.Indexation.UpsertArticle:output_type -> indexation.UpsertArticleResponse
	3, // 5: indexation.Indexation.UpsertArticles:output_type -> indexation.UpsertArticlesResponse
	6, // 6: indexation.Indexation.GetArticles:output_type -> indexation.GetArticlesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_indexation_indexation_proto_init() }
func file_indexation_indexation_proto_init() {
	if File_indexation_indexation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexation_indexation_proto_rawDesc), len(file_indexation_indexation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexation_indexation_proto_goTypes,
		DependencyIndexes: file_indexation_indexation_proto_depIdxs,
		EnumInfos:         file_indexation_indexation_proto_enumTypes,
		MessageInfos:      file_indexation_indexation_proto_msgTypes,
	}.Build()
	File_indexation_indexation_proto = out.File
	file_indexation_indexation_proto_goTypes = nil
	file_indexation_indexation_proto_depIdxs = nil
}
